services:
  - type: web
    name: face-checkin-backend
    env: python
    region: singapore
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: CMAKE_BUILD_PARALLEL_LEVEL
        value: "1"
      - key: MAX_JOBS
        value: "1"

  - type: web
    name: face-checkin-frontend
    env: static
    region: singapore
    buildCommand: ""
    staticPublishPath: "./"
